name = "card-pdf-generator"
description = "A web application to generate card PDFs from CSV files"

packages = [
    "pandas",
    "fpdf2",
    "qrcode",
    "pillow"
]

[files]
"./src/config.py" = "./src/config.py"
"./src/pdf.py" = "./src/pdf.py"
